### ISSUE TITLE
Enable Netlify hosting for documentation

### ISSUE THREAD

**Issue by brylie** [creativecommons/vocabulary-components#22]
We recently merged a VuePress documentation pull request. Now we can host the docs. Netlify is a good option for hosting since it doesn't require us to keep the documentation build output under revision control as would GitHub pages.

![image](https://user-images.githubusercontent.com/17307/154020671-6f6e4346-95ac-4736-9f3c-a44997467fe1.png)

## Task

- [ ] enable Netlify hosting for documentation

**Comment by possumbilities** [comment]
Closing this, since this is moving to archived, and no longer on the roadmp
