### ISSUE TITLE
Grammatical mistakes in Readme

### ISSUE THREAD

**Issue by Lakshay-Pruthi** [creativecommons/vocabulary-components#25]
## Description
The README file contains grammatical errors, such as missing commas and other issues, which could affect its clarity and readability.

## Reproduction
1. Read the Readme file
2. See error.

## Expectation
Documentation should be clear and readable.

## Screenshots
![image](https://user-images.githubusercontent.com/91469717/223040065-59461f57-853a-4fb0-8288-9e99def0958b.png)
![image](https://user-images.githubusercontent.com/91469717/223040149-c785e3ed-dc95-4845-88ab-4ae9410eac03.png)

and many more small mistakes

## Resolution

- [x] I would be interested in resolving this bug.

**Comment by Sanjeevliv** [comment]
I am on it.
