### ISSUE TITLE
[Feature] Upgrade project to Vue 3

### ISSUE THREAD

**Issue by MuluhGodson** [creativecommons/vocabulary-components#8]
## Problem
This project still uses Vue 2.x 

## Description
Vue 3.0 was released in [2020](https://github.com/vuejs/vue-next/releases/tag/v3.0.0). The dependency problems in the original vocabulary project slowed down efforts to upgrade these components to Vue 3. Now that these components have been separated into a separate project/repo, it gives room for a proper upgrade to Vue 3.

## Alternatives
Continue using Vue 2.x but this will mean less support from the Vue Ecosystem as Vue 2 reaches end-of-life.

## Additional context
:warning:  No support for IE 11 in Vue 3.x

## Implementation

- [ ] I would be interested in implementing this feature.

**Comment by possumbilities** [comment]
Closing this, since this is moving to archived, and no longer on the roadmap
